apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage-db
spec:
  selector:
    matchLabels:
      app: mypage-db
  template:
    metadata:
      labels:
        app: mypage-db
    spec:
      containers:
        - name: mypage-db
          image: postgres:13
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: mypage